# Generated by Django 2.2.5 on 2019-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quest_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='title',
            field=models.TextField(default='test quest'),
            preserve_default=False,
        ),
    ]
